"""Rotas do domínio de professores."""

from django.urls import path

from apps.professores.views import (
    BuscaTurmasAtribuidasProfessoresEscolaView,
    EscolaFuncionariosCargosView,
    EscolaFuncionariosCargoView,
    EscolaFuncionariosFuncaoAtividadeView,
    EscolaFuncionariosFuncaoExternaView,
    EscolaFuncionariosFuncoesAtividadesView,
    EscolaFuncionariosFuncoesExternasView,
    EscolaFuncionariosView,
    FuncionarioAtivoView,
    FuncionarioPerfilTurmasView,
    FuncionariosBuscarPorListaRfView,
    FuncionariosBuscarTurmasElegiveisView,
    FuncionariosTurmasView,
    FuncionariosView,
    NomeServidorView,
    NomeUsuarioEolView,
    ProfessorAutoCompleteView,
    ProfessorBuscarPorRfDreUeView,
    ProfessorBuscarPorRfView,
    ProfessorBuscarTurmasAtribuidasView,
    ProfessorBuscaTurmasAtribuidasEscolaView,
    ProfessorDisciplinaTurmasView,
    ProfessorEhEmeiView,
    ProfessoresBuscarPorListaRfAnoView,
    ProfessorTurmasView,
    ProfessorView,
    ValidadeProfessorView,
)

urlpatterns = [
    path(
        "funcionarios/<str:login>/perfis/<str:id_perfil>/turmas/",
        FuncionarioPerfilTurmasView.as_view(),
    ),
    path(
        "funcionarios/turmas/",
        FuncionariosTurmasView.as_view(),
    ),
    path(
        "funcionarios/BuscarTurmasElegiveis/",
        FuncionariosBuscarTurmasElegiveisView.as_view(),
    ),
    path(
        "funcionarios/",
        FuncionariosView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/BuscarPorRf/<int:ano_letivo>/",
        ProfessorBuscarPorRfView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/BuscarPorRfDreUe/<int:ano_letivo>/",
        ProfessorBuscarPorRfDreUeView.as_view(),
    ),
    path(
        "professores/<int:ano_letivo>/BuscarPorListaRF/",
        ProfessoresBuscarPorListaRfAnoView.as_view(),
    ),
    path(
        "professores/<int:ano_letivo>/AutoComplete/<str:dre_id>/",
        ProfessorAutoCompleteView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/ehEmei/",
        ProfessorEhEmeiView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/turmas/",
        ProfessorTurmasView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/disciplina/<str:disciplina_id>/turmas/",
        ProfessorDisciplinaTurmasView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/validade/",
        ValidadeProfessorView.as_view(),
    ),
    path(
        "professores/<str:rf_professor>/",
        ProfessorView.as_view(),
    ),
    path(
        "acessos/funcionario-ativo/<str:registro_funcional>/",
        FuncionarioAtivoView.as_view(),
    ),
    path(
        "funcionarios/nome-servidor/<str:registro_funcional>/",
        NomeServidorView.as_view(),
    ),
    path(
        "funcionarios/nome-usuario-eol/<str:registro_funcional>/",
        NomeUsuarioEolView.as_view(),
    ),
    path(
        "funcionarios/BuscarPorListaRF/",
        FuncionariosBuscarPorListaRfView.as_view(),
    ),
    path(
        "escolas/<str:codigo_ue>/funcionarios/funcoes-atividades/"
        "<str:codigo_funcao_atividade>/",
        EscolaFuncionariosFuncaoAtividadeView.as_view(),
    ),
    path(
        "escolas/<str:codigo_ue>/funcionarios/funcoes-atividades/",
        EscolaFuncionariosFuncoesAtividadesView.as_view(),
    ),
    path(
        "escolas/<str:codigo_ue>/funcionarios/funcoes-externas/"
        "<str:codigo_funcao_externa>/",
        EscolaFuncionariosFuncaoExternaView.as_view(),
    ),
    path(
        "escolas/<str:codigo_ue>/funcionarios/funcoes-externas/",
        EscolaFuncionariosFuncoesExternasView.as_view(),
    ),
    path(
        "escolas/<str:codigo_ue>/funcionarios/cargos/",
        EscolaFuncionariosCargosView.as_view(),
    ),
    path(
        "escolas/<str:codigo_ue>/funcionarios/cargos/<str:codigo_cargo>/",
        EscolaFuncionariosCargoView.as_view(),
    ),
    path(
        "escolas/<str:codigo_ue>/funcionarios/",
        EscolaFuncionariosView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/escolas/<str:codigo_eol_escola>/turmas/anos_letivos/<int:ano_letivo>/",
        ProfessorBuscaTurmasAtribuidasEscolaView.as_view(),
    ),
    path(
        "professores/escolas/<str:codigo_eol_escola>/turmas/anos_letivos/<int:ano_letivo>/",
        BuscaTurmasAtribuidasProfessoresEscolaView.as_view(),
    ),
    path(
        "professores/<str:codigo_rf>/turmas/anos_letivos/<int:ano_letivo>/",
        ProfessorBuscarTurmasAtribuidasView.as_view(),
    ),
]
