"""Rotas do domínio pedagógico."""

from django.urls import path

from apps.pedagogico.views import (
    ComponentesCurricularesViewSet,
    ComponentesFuncionarioViewSet,
    ComponentesPlanejamentoViewSet,
    ComponentesPorListaTurmasViewSet,
    ComponentesRegenciaViewSet,
    ComponentesSemAtribuicaoViewSet,
    ComponentesTurmaAnoViewSet,
    ComponentesTurmaFuncionarioViewSet,
    ComponentesTurmaProgramaViewSet,
    ComponentesTurmasRegularesViewSet,
    ComponentesTurmaViewSet,
    DadosAulaTurmaViewSet,
    DadosTurmaViewSet,
    GradeComponentesCurricularesViewSet,
    ItinerariosEnsinoMedioViewSet,
    ListarTurmasViewSet,
    SincronizacaoInstitucionalTurmaViewSet,
    SincronizacoesInstitucionaisAnosLetivosViewSet,
    TurmasHistoricasGeraisProfessorViewSet,
    TurmasProgramaViewSet,
    TurmasRegularesViewSet,
    ValidarComponentePapViewSet,
)

turma_urlpatterns = [
    path(
        "anos-letivos/<int:ano_letivo>/professor/"
        + "<str:professor_rf>/turmas-historicas-geral/",
        TurmasHistoricasGeraisProfessorViewSet.as_view(),
        name="turmas-historicas-gerais-professor",
    ),
    path(
        "itinerario/ensino-medio/",
        ItinerariosEnsinoMedioViewSet.as_view(),
        name="itinerarios-ensino-medio",
    ),
    path(
        "ue/<str:codigo_ue>/" "sincronizacoes-institucionais/anos-letivos/",
        SincronizacoesInstitucionaisAnosLetivosViewSet.as_view(),
        name="sincronizacoes-institucionais-anos-letivos",
    ),
    path(
        "ues/<str:codigo_ue>/turmas/<str:codigo_turma>/"
        "sincronizacoes-institucionais/",
        SincronizacaoInstitucionalTurmaViewSet.as_view(),
        name="sincronizacao-institucional-turma",
    ),
    path(
        "turmas-regulares/",
        TurmasRegularesViewSet.as_view(),
    ),
    path(
        "turmas-programa/",
        TurmasProgramaViewSet.as_view(),
    ),
    path(
        "listar-turmas/",
        ListarTurmasViewSet.as_view(),
    ),
    path(
        "<str:codigo_turma>/dados/",
        DadosTurmaViewSet.as_view(),
    ),
]

urlpatterns = [
    path(
        "turmas/regulares/",
        ComponentesTurmasRegularesViewSet.as_view(),
    ),
    path(
        "turmas/",
        ComponentesPorListaTurmasViewSet.as_view(),
    ),
    path(
        "dados-aula-turma/",
        DadosAulaTurmaViewSet.as_view(),
    ),
    path(
        "anos/<int:ano_turma>/regencia/",
        ComponentesRegenciaViewSet.as_view(),
    ),
    path(
        "turmas/<str:codigo_turma>/funcionarios/<str:login>/"
        "perfis/<str:id_perfil>/agrupaComponenteCurricular/"
        "<str:agrupa_componente_curricular>/",
        ComponentesTurmaFuncionarioViewSet.as_view(),
    ),
    path(
        "turmas/<str:codigo_turma>/funcionarios/<str:login>/"
        "perfis/<str:id_perfil>/planejamento/",
        ComponentesPlanejamentoViewSet.as_view(),
    ),
    path(
        "turmas/<str:codigo_turma>/sem-atribuicao/" "<int:data_base_tick>/",
        ComponentesSemAtribuicaoViewSet.as_view(),
    ),
    path(
        "turmas/<str:codigo_turma>/funcionarios/<str:login>/"
        "perfis/<str:id_perfil>/validar/pap/",
        ValidarComponentePapViewSet.as_view(),
    ),
    path(
        "funcionarios/<str:login>/perfis/<str:id_perfil>/",
        ComponentesFuncionarioViewSet.as_view(),
    ),
    path(
        "ues/<str:ue_id>/modalidades/<int:modalidade>/anos/<int:ano_letivo>/anos-escolares/",
        ComponentesTurmaAnoViewSet.as_view(),
    ),
    path(
        "ues/<str:ue_id>/modalidades/<int:modalidade>/anos/<int:ano_letivo>/",
        ComponentesTurmaProgramaViewSet.as_view(),
    ),
    path(
        "ues/<str:ue_id>/turmas/",
        ComponentesTurmaViewSet.as_view(),
    ),
    path(
        "ano-turma/ano-letivo/<int:ano_letivo>/",
        GradeComponentesCurricularesViewSet.as_view(),
    ),
    path(
        "",
        ComponentesCurricularesViewSet.as_view(),
    ),
]
